# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BeszelAgent < Formula
  desc "Agent for Beszel, a lightweight server monitoring platform."
  homepage "https://beszel.dev"
  version "0.12.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/henrygd/beszel/releases/download/v0.12.3/beszel-agent_darwin_amd64.tar.gz"
      sha256 "80428f07128fad2fd15fd5dcc50202b24a6686e49d97138ea606a459b05780a3"

      def install
        bin.install "beszel-agent"
        (bin/"beszel-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/beszel/beszel-agent.env" ]; then
            source "$HOME/.config/beszel/beszel-agent.env"
          fi
          set +a
          exec #{bin}/beszel-agent "$@"
        EOS
        (bin/"beszel-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/henrygd/beszel/releases/download/v0.12.3/beszel-agent_darwin_arm64.tar.gz"
      sha256 "6ffce0b9c195cd0a73e95af329f946a0ec156edc6f71327f14959ea18539b1cd"

      def install
        bin.install "beszel-agent"
        (bin/"beszel-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/beszel/beszel-agent.env" ]; then
            source "$HOME/.config/beszel/beszel-agent.env"
          fi
          set +a
          exec #{bin}/beszel-agent "$@"
        EOS
        (bin/"beszel-agent-launcher").chmod 0755
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/henrygd/beszel/releases/download/v0.12.3/beszel-agent_linux_amd64.tar.gz"
      sha256 "c024f482fd07ed23918385146afc8e38f8d1534fe7f6f2f373eb5b371166c6ac"
      def install
        bin.install "beszel-agent"
        (bin/"beszel-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/beszel/beszel-agent.env" ]; then
            source "$HOME/.config/beszel/beszel-agent.env"
          fi
          set +a
          exec #{bin}/beszel-agent "$@"
        EOS
        (bin/"beszel-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/henrygd/beszel/releases/download/v0.12.3/beszel-agent_linux_arm.tar.gz"
      sha256 "d985bbefa352f4e96dd5414454cf13d6361a3e7480896b6a83553bd49d3a4bb3"
      def install
        bin.install "beszel-agent"
        (bin/"beszel-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/beszel/beszel-agent.env" ]; then
            source "$HOME/.config/beszel/beszel-agent.env"
          fi
          set +a
          exec #{bin}/beszel-agent "$@"
        EOS
        (bin/"beszel-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/henrygd/beszel/releases/download/v0.12.3/beszel-agent_linux_arm64.tar.gz"
      sha256 "2e145548aaf36dd8a8c32bd60a7f98ca1b7454857308c6b9a3c3757f7571f4e1"
      def install
        bin.install "beszel-agent"
        (bin/"beszel-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/beszel/beszel-agent.env" ]; then
            source "$HOME/.config/beszel/beszel-agent.env"
          fi
          set +a
          exec #{bin}/beszel-agent "$@"
        EOS
        (bin/"beszel-agent-launcher").chmod 0755
      end
    end
  end

  service do
    run ["#{bin}/beszel-agent-launcher"]
    log_path "#{Dir.home}/.cache/beszel/beszel-agent.log"
    error_log_path "#{Dir.home}/.cache/beszel/beszel-agent.log"
    keep_alive true
    restart_delay 5
    process_type :background
  end
end
