# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BeszelAgent < Formula
  desc "Agent for Beszel, a lightweight server monitoring platform."
  homepage "https://beszel.dev"
  version "0.15.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/henrygd/beszel/releases/download/v0.15.1/beszel-agent_darwin_amd64.tar.gz"
      sha256 "b9be4814ff1292da953c10d7d49d3002e1a765fdd2358b63c4268845b2545af6"

      def install
        bin.install "beszel-agent"
        (bin/"beszel-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/beszel/beszel-agent.env" ]; then
            source "$HOME/.config/beszel/beszel-agent.env"
          fi
          set +a
          exec #{bin}/beszel-agent "$@"
        EOS
        (bin/"beszel-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/henrygd/beszel/releases/download/v0.15.1/beszel-agent_darwin_arm64.tar.gz"
      sha256 "b058b0f8729417739b3be7833acf57d7a11c002cc41154091a6a7ee6ccca9c19"

      def install
        bin.install "beszel-agent"
        (bin/"beszel-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/beszel/beszel-agent.env" ]; then
            source "$HOME/.config/beszel/beszel-agent.env"
          fi
          set +a
          exec #{bin}/beszel-agent "$@"
        EOS
        (bin/"beszel-agent-launcher").chmod 0755
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/henrygd/beszel/releases/download/v0.15.1/beszel-agent_linux_amd64.tar.gz"
      sha256 "0ddd453aaabb767a21ab4095c56deb1e53a9ca70d941afd4544fedffceb00735"
      def install
        bin.install "beszel-agent"
        (bin/"beszel-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/beszel/beszel-agent.env" ]; then
            source "$HOME/.config/beszel/beszel-agent.env"
          fi
          set +a
          exec #{bin}/beszel-agent "$@"
        EOS
        (bin/"beszel-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/henrygd/beszel/releases/download/v0.15.1/beszel-agent_linux_arm.tar.gz"
      sha256 "fc274f6f8c5b9b7afe831be65b7d7f2fbf5a5eb1369335900ae931569ae932b2"
      def install
        bin.install "beszel-agent"
        (bin/"beszel-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/beszel/beszel-agent.env" ]; then
            source "$HOME/.config/beszel/beszel-agent.env"
          fi
          set +a
          exec #{bin}/beszel-agent "$@"
        EOS
        (bin/"beszel-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/henrygd/beszel/releases/download/v0.15.1/beszel-agent_linux_arm64.tar.gz"
      sha256 "094f3fb602f3f60bf145fea5299692a9d72839183610feeaaa66b53c714c6e57"
      def install
        bin.install "beszel-agent"
        (bin/"beszel-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/beszel/beszel-agent.env" ]; then
            source "$HOME/.config/beszel/beszel-agent.env"
          fi
          set +a
          exec #{bin}/beszel-agent "$@"
        EOS
        (bin/"beszel-agent-launcher").chmod 0755
      end
    end
  end

  service do
    run ["#{bin}/beszel-agent-launcher"]
    log_path "#{Dir.home}/.cache/beszel/beszel-agent.log"
    error_log_path "#{Dir.home}/.cache/beszel/beszel-agent.log"
    keep_alive true
    restart_delay 5
    process_type :background
  end
end
