# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BeszelAgent < Formula
  desc "Agent for Beszel, a lightweight server monitoring platform."
  homepage "https://beszel.dev"
  version "0.18.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/henrygd/beszel/releases/download/v0.18.6/beszel-agent_darwin_amd64.tar.gz"
      sha256 "c95612fd45dc0adcf0f722f32a33a5142a689b43968766e7908af91ea4a03b4c"

      define_method(:install) do
        bin.install "beszel-agent"
        (bin/"beszel-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/beszel/beszel-agent.env" ]; then
            source "$HOME/.config/beszel/beszel-agent.env"
          fi
          set +a
          exec #{bin}/beszel-agent "$@"
        EOS
        (bin/"beszel-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/henrygd/beszel/releases/download/v0.18.6/beszel-agent_darwin_arm64.tar.gz"
      sha256 "73a59fd97c2a630d8c342acd2dd2c15b283cee6ca9c08280385f7cda6bca94f6"

      define_method(:install) do
        bin.install "beszel-agent"
        (bin/"beszel-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/beszel/beszel-agent.env" ]; then
            source "$HOME/.config/beszel/beszel-agent.env"
          fi
          set +a
          exec #{bin}/beszel-agent "$@"
        EOS
        (bin/"beszel-agent-launcher").chmod 0755
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/henrygd/beszel/releases/download/v0.18.6/beszel-agent_linux_amd64.tar.gz"
      sha256 "93d32209ffe6c47ce9cb642cf60653abbe8997c69b6677eba28c792948d2b5f5"
      define_method(:install) do
        bin.install "beszel-agent"
        (bin/"beszel-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/beszel/beszel-agent.env" ]; then
            source "$HOME/.config/beszel/beszel-agent.env"
          fi
          set +a
          exec #{bin}/beszel-agent "$@"
        EOS
        (bin/"beszel-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/henrygd/beszel/releases/download/v0.18.6/beszel-agent_linux_arm.tar.gz"
      sha256 "5869e2f244f9c6e4dcb5ed377d452de532a104096a32acd308c3f8f0ce82256f"
      define_method(:install) do
        bin.install "beszel-agent"
        (bin/"beszel-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/beszel/beszel-agent.env" ]; then
            source "$HOME/.config/beszel/beszel-agent.env"
          fi
          set +a
          exec #{bin}/beszel-agent "$@"
        EOS
        (bin/"beszel-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/henrygd/beszel/releases/download/v0.18.6/beszel-agent_linux_arm64.tar.gz"
      sha256 "70d04e4d15f2714999529d5788838e9b0eb99fa2b054042d22a6a0a34a458d99"
      define_method(:install) do
        bin.install "beszel-agent"
        (bin/"beszel-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/beszel/beszel-agent.env" ]; then
            source "$HOME/.config/beszel/beszel-agent.env"
          fi
          set +a
          exec #{bin}/beszel-agent "$@"
        EOS
        (bin/"beszel-agent-launcher").chmod 0755
      end
    end
  end

  service do
    run ["#{bin}/beszel-agent-launcher"]
    log_path "#{Dir.home}/.cache/beszel/beszel-agent.log"
    error_log_path "#{Dir.home}/.cache/beszel/beszel-agent.log"
    keep_alive true
    restart_delay 5
    process_type :background
  end
end
